import { useState, useRef } from 'react';
import { useApp } from '../context/AppContext';
import { FileText, Play, Printer, Download } from 'lucide-react';
import api from '../services/api';

export default function CAMReport() {
  const { state, dispatch, showLoading, hideLoading, toast } = useApp();
  const [camHtml, setCamHtml] = useState('');
  const iframeRef = useRef();

  const buildPayload = () => {
    const c = state.company;
    return {
      company: {
        company_name: c.company_name || 'Company',
        cin: c.cin || '',
        pan: c.pan || '',
        gstin: c.gstin || '',
        industry: c.industry || 'Manufacturing',
        sub_sector: c.sector || '',
        incorporation_date: c.incorporation_date || '',
        registered_address: c.registered_address || '',
        promoters: c.promoter_names ? c.promoter_names.split(',').map(s => s.trim()) : [],
      },
      loan_request: {
        requested_amount: (parseFloat(c.loan_amount) || 0) / 100000,
        loan_purpose: c.loan_purpose || 'Working Capital',
        tenure_months: (parseInt(c.loan_tenure) || 5) * 12,
        collateral_description: c.collateral_type || '',
        collateral_value: (parseFloat(c.collateral_value) || 0) / 100000,
      },
      financial_data: (state.financialYears || []).map(y => ({
        year: y.year,
        revenue: parseFloat(y.revenue) || 0,
        ebitda: parseFloat(y.ebitda) || 0,
        pat: parseFloat(y.pat) || 0,
        total_assets: parseFloat(y.total_assets) || 0,
        total_liabilities: parseFloat(y.total_liabilities) || 0,
        net_worth: parseFloat(y.net_worth) || 0,
        current_assets: parseFloat(y.current_assets) || 0,
        current_liabilities: parseFloat(y.current_liabilities) || 0,
      })),
      gst_data: [],
      bank_data: [],
      primary_insights: (state.insights || []).map(i => ({
        category: i.category === 'operations' ? 'site_visit' : i.category === 'management' ? 'management_interview' : i.category,
        observation: i.observation,
        severity: i.impact === 'positive' ? 'positive' : i.impact === 'negative' ? 'warning' : 'info',
        impact_area: i.category,
      })),
    };
  };

  const generateFromData = async () => {
    if ((state.financialYears || []).length === 0) {
      toast('Add financial data first on the Financial Analysis page', 'warning');
      return;
    }
    showLoading('Generating CAM from your data...');
    try {
      const payload = buildPayload();
      // Try HTML endpoint first for nice rendering
      try {
        const htmlResult = await api.generateCAMHtml(payload);
        if (htmlResult?.html) {
          setCamHtml(htmlResult.html);
        }
      } catch {
        // HTML generation failed, will use fallback below
      }
      // Also run full pipeline for JSON data
      const result = await api.generateCAM(payload);
      dispatch({ type: 'SET_CAM', payload: result });
      dispatch({ type: 'SET_SCORING', payload: result });
      if (!camHtml) buildFallbackHtml(result);
      toast('CAM generated from your data!', 'success');
    } catch (e) {
      toast(e.message, 'error');
    } finally {
      hideLoading();
    }
  };

  const buildFallbackHtml = (data) => {
    const report = data?.report || data;
    const html = `<!DOCTYPE html>
<html><head><style>
body{font-family:'Georgia',serif;max-width:900px;margin:auto;padding:40px;color:#333;line-height:1.6}
h1{color:#1a237e;border-bottom:3px double #1a237e;padding-bottom:10px}
h2{color:#1a237e;border-bottom:1px solid #ddd;padding-bottom:6px;margin-top:30px}
table{width:100%;border-collapse:collapse;margin:20px 0}
th{background:#1a237e;color:white;padding:10px;text-align:left}
td{padding:10px;border-bottom:1px solid #eee}
tr:nth-child(even){background:#f5f5f5}
.conf{text-align:center;color:red;font-weight:bold;border:2px solid red;padding:5px;margin-bottom:20px}
pre{background:#f5f5f5;padding:20px;border-radius:8px;overflow:auto;font-size:12px}
</style></head><body>
<div class="conf">⚠ CONFIDENTIAL - FOR INTERNAL USE ONLY</div>
<h1>📋 Credit Appraisal Memo</h1>
<h2>Full Report Data</h2>
<pre>${JSON.stringify(report, null, 2)}</pre>
<hr><p style="text-align:center;color:#999;font-size:12px">Generated by IntelCredit AI Engine | ${new Date().toLocaleString()}</p>
</body></html>`;
    setCamHtml(html);
  };

  const printCAM = () => {
    if (iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.print();
    } else {
      toast('Generate a CAM report first', 'warning');
    }
  };

  const downloadJSON = () => {
    if (!state.camReport) { toast('Generate a report first', 'warning'); return; }
    const blob = new Blob([JSON.stringify(state.camReport, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `CAM_Report_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    toast('CAM data downloaded!', 'success');
  };

  return (
    <>
      <p className="section-desc">Generate a comprehensive Credit Appraisal Memo with all analysis, scoring, and recommendations.</p>

      {/* Controls */}
      <div className="cam-controls">
        <button className="btn btn-primary btn-lg" onClick={generateFromData}>
          <FileText size={18} /> Generate CAM Report
        </button>
        {camHtml && (
          <>
            <button className="btn btn-outline" onClick={printCAM}><Printer size={16} /> Print</button>
            <button className="btn btn-outline" onClick={downloadJSON}><Download size={16} /> Download JSON</button>
          </>
        )}
      </div>

      {/* CAM Preview */}
      {camHtml ? (
        <div className="cam-frame">
          <iframe ref={iframeRef} srcDoc={camHtml} title="CAM Report" style={{ width: '100%', border: 'none', minHeight: 800 }} />
        </div>
      ) : (
        <div className="card" style={{ textAlign: 'center', padding: 60 }}>
          <FileText size={64} color="var(--border)" />
          <h3 style={{ color: 'var(--text-secondary)', marginTop: 16 }}>No CAM Generated Yet</h3>
          <p className="hint">Click "Generate CAM Report" after entering company and financial data</p>
        </div>
      )}
    </>
  );
}
